---
title: "Demonstration"
author: "Adam Thrash"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Using PAST

The following block of code calls the `merge()` function of PAST with example data, loads the LD data, and gets tagSNPs with associated genes. This documentation will be extended as the software is developed.

```{r}
# past should load plyr/dplyr
source("http://bioconductor.org/biocLite.R")
biocLite("qvalue")
library(qvalue)
library(dplyr)
library(past)
library(parallel)
library(foreach)
library(doParallel)
library(ggplot2)

all_data <- merge_data("../example/KernelColor.statistics.txt", "../example/KernelColor.effects.txt")
LD <- parse_LD("../example/KernelColorLD.txt.gz") # parse_LD can take gzip-compressed files or plain text
genes <-parse_SNP(all_data, LD, "../example/genes.gff3.gz", 1000, 0.8, 4)
rugplots_data_resistant <- find_significant_pathways(genes, "../example/pathways.txt", 5, "resistant", 1000, 4)
rugplots_data_susceptible <- find_significant_pathways(genes, "../example/pathways.txt", 5, "susceptible", 1000, 4)
plot_pathways(rugplots_data_susceptible, "pvalue", 0.02, "susceptible", "../example/results/")
plot_pathways(rugplots_data_resistant, "pvalue", 0.02, "resistant", "../example/results/")
```